date:
  dilbert:
    uri: 'https://dilbert.com/strip/{year}-{month}-{day}'
    indicator: "twitter:image"
    regex: "https.*assets.amuni.*"
    extension: gif
    schedule: "*"
  doonesbury:
    uri: 'http://gocomics.com/doonesbury/{year}/{month}/{day}'
    indicator: 'feature_item"'
    regex: "http://assets.amuniversal.com/[a-f0-9]+"
    extension: 'gif'
    schedule: "*"
  calvin:
    uri: 'http://gocomics.com/calvinandhobbes/{year}/{month}/{day}'
    indicator: 'feature_item"'
    regex: "http://assets.amuniversal.com/[a-f0-9]+"
    extension: 'gif'
    schedule: "*"
  foxtrot:
    uri: 'http://gocomics.com/foxtrot/{year}/{month}/{day}'
    indicator: 'feature_item"'
    regex: "http://assets.amuniversal.com/[a-f0-9]+"
    extension: 'gif'
    schedule: "0"
  forbetterorforworse:
    uri: 'http://gocomics.com/forbetterorforworse/{year}/{month}/{day}'
    indicator: 'feature_item"'
    regex: "http://assets.amuniversal.com/[a-f0-9]+"
    extension: 'gif'
    schedule: "*"
  mikeluckovich:
    uri: 'http://gocomics.com/mikeluckovich/{year}/{month}/{day}'
    indicator: 'feature_item"'
    regex: "http://assets.amuniversal.com/[a-f0-9]+"
    extension: 'gif'
    schedule: 3
  penny_arcade:
    uri: 'http://penny-arcade.com/comic/{year}/{month}/{day}'
    indicator: 'http://art.penny-arcade.com/photos'
    regex: 'http://art.penny-arcade.com/photos/.*jpg'
    extension: 'jpg'
    schedule: 135
  userfriendly:
    uri: 'http://ars.userfriendly.org/cartoons/?id={year}{month}{day}'
    indicator: '^<a href="\/cartoons\/.*><img border'
    regex: 'http://www.userfriendly.org/cartoons/archives/.*gif'
    extension: 'gif'
    schedule: "*"
offset:
  xkcd:
    uri: 'http://xkcd.com/{offset}'
    key: 2012-12-17,1149
    indicator: hotlinking
    regex: "http://imgs.xkcd.com/comics/.*\\.png"
    extension: png
    schedule: 135
download:
  smbc:
    uri: 'http://www.smbc-comics.com/comics/{year}{month}{day}.gif'
    extension: 'gif'
    schedule: "*"
